echo "hello and ewlcome to the session be regulaer"
echo "hello and ewlcome to the session be regulaer"
echo "hello and ewlcome to the session be regulaer"
echo "hello and ewlcome to the session be regulaer"
echo "hello and ewlcome to the session be regulaer"
echo "hello and ewlcome to the session be regulaer"
echo "hello and ewlcome to the session be regulaer"
